version: '3'
services:
  
  collectd:
    build:
      context: collectd/
    ports:
      - "8080:8080"
    depends_on:
      - kibana

  elasticsearch:
    image: elasticsearch:7.3.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    image: logstash:7.3.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "25826:25826"
      - "9500:9500"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.3.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
